export const patients = [
    {
        id: 1,
        name: "John Doe",
        email: "john@example.com",
        phoneNo: "1234567890",
        time: 1630000000,
        stauts: "Active",
        actions: "Edit",
    },
    {
        id: 2,
        name: "Jane Smith",
        email: "jane@example.com",
        phoneNo: "9876543210",
        time: 1631000000,
        sections: "Inactive",
        actions: "Edit",
    },
    {
        id: 3,
        name: "Alice Johnson",
        email: "alice@example.com",
        phoneNo: "5555555555",
        time: 1632000000,
        sections: "Active",
        actions: "Edit",
    },
];
export const payments = [
    {
        id: 1,
        name: 'John Doe',
        arrival: '2023-08-26',
        treatments: 'Treatments',
        amount: 150,
        paid: 'Yes',
        action: 'Edit',
    },
    {
        id: 2,
        name: 'Jane Smith',
        arrival: '2023-08-27',
        treatments: 'Treatments',
        amount: 100,
        paid: 'No',
        action: 'Edit',
    },
    {
        id: 3,
        name: 'Alice Johnson',
        arrival: '2023-08-28',
        treatments: 'Treatments',
        amount: 50,
        paid: 'Yes',
        action: 'Edit',
    },
    {
        id: 4,
        name: 'Robert Brown',
        arrival: '2023-08-29',
        treatments: 'Treatments',
        amount: 200,
        paid: 'Yes',
        action: 'Edit',
    },
    {
        id: 5,
        name: 'Emily Wilson',
        arrival: '2023-08-30',
        treatments: 'Treatments',
        amount: 100,
        paid: 'No',
        action: 'Edit',
    },
    {
        id: 6,
        name: 'Daniel Johnson',
        arrival: '2023-08-31',
        treatments: 'Treatments',
        amount: 50,
        paid: 'Yes',
        action: 'Edit',
    },
    {
        id: 7,
        name: 'Sophia Lee',
        arrival: '2023-09-01',
        treatments: 'Treatments',
        amount: 150,
        paid: 'Yes',
        action: 'Edit',
    },
]
export const leads = [
    {
        id: 1,
        name: "John Doe",
        email: "john@example.com",
        phoneNo: "123-456-7890",
        creationTime: "2023-08-27 10:00:00",
        status: "Active",
        actions: "Edit/Delete",
    },
    {
        id: 2,
        name: "Jane Smith",
        email: "jane@example.com",
        phoneNo: "987-654-3210",
        creationTime: "2023-08-26 14:30:00",
        status: "Inactive",
        actions: "Edit/Delete",
    },
];
export
    const schedule = [
        {
            id: 1,
            name: "John Doe",
            arrivalDate: "2023-08-26",
            airpot: "JFK",
            flightNo: "ABC123",
            departureDate: "2023-08-30",
            hotelName: "Grand Hotel",
        },
        {
            id: 2,
            name: "Jane Smith",
            arrivalDate: "2023-08-27",
            airpot: "LHR",
            flightNo: "DEF456",
            departureDate: "2023-08-31",
            hotelName: "Luxury Resort",
        },
        {
            id: 3,
            name: "Jane Smith",
            arrivalDate: "2023-08-27",
            airpot: "LHR",
            flightNo: "DEF456",
            departureDate: "2023-08-31",
            hotelName: "Luxury Resort",
        },
    ];